"""Initial MySQL migration with GUID type

Revision ID: 3e0ea717187f
Revises: 
Create Date: 2026-09-06 22:35:29.472027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# MySQL-compatible GUID type (CHAR(36))
GUID = sa.CHAR(36)

# revision identifiers, used by Alembic.
revision: str = '3e0ea717187f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', GUID, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios'))
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_table('consultas_chat',
    sa.Column('id', GUID, nullable=False),
    sa.Column('usuario_id', GUID, nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.Column('documentos_fuente', sa.JSON(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_consultas_chat_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultas_chat'))
    )
    op.create_index(op.f('ix_consultas_chat_usuario_id'), 'consultas_chat', ['usuario_id'], unique=False)
    op.create_table('repositorios',
    sa.Column('id', GUID, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('usuario_creador_id', GUID, nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_creador_id'], ['usuarios.id'], name=op.f('fk_repositorios_usuario_creador_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositorios'))
    )
    op.create_table('documentos',
    sa.Column('id', GUID, nullable=False),
    sa.Column('repositorio_id', GUID, nullable=False),
    sa.Column('usuario_carga_id', GUID, nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('formato', sa.String(length=10), nullable=False),
    sa.Column('ruta_almacenamiento', sa.String(length=500), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.Column('campos_extraidos', sa.JSON(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('procesado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repositorio_id'], ['repositorios.id'], name=op.f('fk_documentos_repositorio_id_repositorios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_carga_id'], ['usuarios.id'], name=op.f('fk_documentos_usuario_carga_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documentos'))
    )
    op.create_index(op.f('ix_documentos_categoria'), 'documentos', ['categoria'], unique=False)
    op.create_index(op.f('ix_documentos_estado'), 'documentos', ['estado'], unique=False)
    op.create_table('fragmentos',
    sa.Column('id', GUID, nullable=False),
    sa.Column('documento_id', GUID, nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('vector_id', sa.String(length=100), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], name=op.f('fk_fragmentos_documento_id_documentos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fragmentos'))
    )
    op.create_index(op.f('ix_fragmentos_documento_id'), 'fragmentos', ['documento_id'], unique=False)
    op.create_index(op.f('ix_fragmentos_vector_id'), 'fragmentos', ['vector_id'], unique=True)
    op.create_table('logs_procesamiento',
    sa.Column('id', GUID, nullable=False),
    sa.Column('documento_id', GUID, nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], name=op.f('fk_logs_procesamiento_documento_id_documentos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logs_procesamiento'))
    )
    op.create_index(op.f('ix_logs_procesamiento_documento_id'), 'logs_procesamiento', ['documento_id'], unique=False)
    op.create_index(op.f('ix_logs_procesamiento_tipo'), 'logs_procesamiento', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_procesamiento_tipo'), table_name='logs_procesamiento')
    op.drop_index(op.f('ix_logs_procesamiento_documento_id'), table_name='logs_procesamiento')
    op.drop_table('logs_procesamiento')
    op.drop_index(op.f('ix_fragmentos_vector_id'), table_name='fragmentos')
    op.drop_index(op.f('ix_fragmentos_documento_id'), table_name='fragmentos')
    op.drop_table('fragmentos')
    op.drop_index(op.f('ix_documentos_estado'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_categoria'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_table('repositorios')
    op.drop_index(op.f('ix_consultas_chat_usuario_id'), table_name='consultas_chat')
    op.drop_table('consultas_chat')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###